version: '3'
services:
    frontend:
        build: ./
        restart: always        
        ports:    
            - "3000:3000"
        volumes:
            - /www/static
    frontendweb:
        image: nginx:latest
        restart: always
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - /config/frontend/conf.d/nginx.conf:/etc/nginx/nginx.conf
        links:
            - frontend:frontend  